name: DesigniteJava Action
description: Analyzes the newly commited code, detects comprehensive set of code smells, and archives the results.
branding:
    color: 'orange'
    icon: 'arrow-up-right' 
inputs:
  PAT:
    description: 'Personal access token'
    default: 'No PAT provided'
  D_KEY:
    description: 'Designite license key - optional'
    default: 'No key'
  API_KEY:
    description: "DCode API key for authentication"
    required: false
  PROJECT_ID:
    description: "DCode project ID"
    required: false

runs:
  using: "composite"
  steps:
    - name: set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'adopt'
    - name: Download DesigniteJava
      run: wget "https://www.designite-tools.com/assets/DesigniteJava.jar"
      shell: sh
    - name: Analyze project with DesigniteJava and archive the results
      run: |
          if [[ "${{inputs.D_KEY}}" == "No key" ]]; then
          java -jar DesigniteJava.jar -ci -repo $GITHUB_REPOSITORY -pat ${{ inputs.PAT }} -o "designite-output" -g
          fi
          if [[ "${{inputs.D_KEY}}" != "No key" ]]; then
          java -jar DesigniteJava.jar -ci -repo $GITHUB_REPOSITORY -pat ${{ inputs.PAT }} -k inputs.D_KEY -o "designite-output" -g
          fi
      shell: bash
    - name: Archive Designite results
      uses: actions/upload-artifact@v4
      with:
        name: designite-output-${{ github.sha }}
        path: "designite-output"
    - name: Store analysis results on DCode platform, if configured. Also, check whether the code passes the configured quality gate
      shell: bash
      run: |
        if [ -n "${{ inputs.API_KEY }}" ]; then
          echo "DCode API key is configured. Uploading the analysis results on DCode..."
          # Build -F arguments with numbered keys file1, file2, ...
          form_args=()
          counter=1
          for file in designite-output/*; do
            if [ -f "$file" ]; then
              form_args+=(-F "file${counter}=@${file}")
              counter=$((counter + 1))
            fi
          done
          if [ ${#form_args[@]} -eq 0 ]; then
            echo "No files found in folder designite-output."
            exit 1
          fi
          # Build curl command (array to handle spaces safely)
          curl_cmd=("curl" "-f" "-s" "-o" "/tmp/curl_output" "-w" "%{http_code}" "-X" "POST" "-H" "X-API-Key: ${{ inputs.API_KEY }}" "-H" "X-Commit-ID: ${{ github.sha }}" "-H" "X-Tool: designiteJava" "${form_args[@]}" "https://dcodehub.com/api/projects/${{ inputs.PROJECT_ID }}/upload/")
          safe_cmd=("${curl_cmd[@]}")
          echo "Executing: ${safe_cmd[*]}"
          http_status=$("${curl_cmd[@]}")
          echo "HTTP status code: $http_status"

          echo "API response:"
          cat /tmp/curl_output
        
          # Check if quality gate is active
          is_active=$(jq -r '.quality_gate.is_active // false' /tmp/curl_output)
          profile=$(jq -r '.quality_gate.profile_name // Unknown' /tmp/curl_output)
        
          if [[ "$is_active" != "true" ]]; then
            echo "::notice::Quality Gate is not active" 
            exit 0
          fi

          # Extract fields
          result=$(echo "$response" | jq -r '.quality_gate.result')

          if [[ "$result" != "PASSED" ]]; then
            echo "::error title=Quality Gate Failed::Profile='$profile'"
            exit 1
          fi
          echo "::notice title=Quality Gate Passed::Profile='$profile'"
        else
          echo "DCode API key not set. Skipping uploading analysis results to DCode."
        fi