name: DesigniteJava Action
description: Analyzes the newly commited code, detects comprehensive set of code smells, and archives the results.
branding:
    color: 'orange'
    icon: 'arrow-up-right' 
inputs:
  PAT:
    description: 'Personal access token'
    default: 'No PAT provided'
  D_KEY:
    description: 'Designite license key - optional'
    default: 'No key'

runs:
  using: "composite"
  steps:
      - name: Download DesigniteJava
        run: wget "https://www.designite-tools.com/assets/DesigniteJava.jar"
        shell: sh
      - name: Analyze project with DesigniteJava and archive the results
        run: |
            if [[ "${{inputs.D_KEY}}" == "No key" ]]; then
            java -jar DesigniteJava.jar -ci -repo $GITHUB_REPOSITORY -pat ${{ inputs.PAT }} -o "designite-output"
            fi
            if [[ "${{inputs.D_KEY}}" != "No key" ]]; then
            java -jar DesigniteJava.jar -ci -repo $GITHUB_REPOSITORY -pat ${{ inputs.PAT }} -k inputs.D_KEY -o "designite-output"
            fi
        shell: bash
      - name: Archive Designite results
        uses: actions/upload-artifact@v4
        with:
          name: designite-output-${{ github.sha }}
          path: "designite-output"
