name: DesigniteJava_action
description: Analyzes the newly commited code, detects comprehensive set of code smells, and uploads the results to QScored.
branding:
    color: 'orange'
    icon: 'arrow-up-right' 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        env:
          QSCORED_API_KEY: ${{ QSCORED_API_KEY }}
          PAT: ${{ PAT }}
          D_KEY: ${{ D_KEY }}
          EMAIL: ${{ EMAIL }}
          PRJ_NAME: {{ PRJ_NAME }}
      - name: Download DesigniteJava
        run: wget "https://www.designite-tools.com/static/download/DJE/DesigniteJava.jar"
      - name: Analyze project with DesigniteJava
        run: |
          java -jar DesigniteJava.jar -ci -repo $GITHUB_REPOSITORY -pat ${{ env.PAT }} -k ${{ env.D_KEY }}
          ls
          curl -X PUT -H "Authorization: Token ${{ env.QSCORED_API_KEY }}" -H "repository-link:https://github.com/" + GITHUB_REPOSITORY -H "username: {{ env.EMAIL }}" -H "Content-Type: mulitpart/form-data" --url "https://qscored.com/api/upload/file.xml?is_open_access=off&version=$GITHUB_RUN_NUMBER&project_name={{ env.PRJ_NAME }}" -F "file=@Designite_output/DesigniteAnalysis.xml"
